# enable this and zprof at the end to debug slow shell startup:
# zmodload zsh/zprof

# enable git prompts, as per
# https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' formats '%F{red}(%b)%f'

# exit code in red, if not 0 & bold blue current path:
# idea: add some red ()s to differentiate from other shell output
#   eg, `fd` tends to prefix output with a blue string
PROMPT='%(?..%F{red}?%?%f )%B%F{blue}%1~%#%f%b '
# show git info and date/time on the right
RPROMPT='${vcs_info_msg_0_} %D %*'

# enable completion:
if type brew &>/dev/null
then
  FPATH="$HOMEBREW_PREFIX/share/zsh/site-functions:${FPATH}"
fi
autoload -Uz compinit
compinit
autoload -U +X bashcompinit && bashcompinit

# vi mode:
bindkey -v

# basic history niceties
# https://scriptingosx.com/2019/06/moving-to-zsh-part-3-shell-options/
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt HIST_IGNORE_SPACE

# generated by /usr/local/opt/fzf/install and lightly edited:
[[ $- == *i* ]] && source "/$HOMEBREW_PREFIX/opt/fzf/shell/completion.zsh" 2> /dev/null
source "/$HOMEBREW_PREFIX/opt/fzf/shell/key-bindings.zsh"

# aliases
# TODO: move to separate file
alias ls='ls -F'
alias unzip='unzip -q' # don't print the names of files being extracted
alias bc='bc -q'
alias tcpdump='sudo tcpdump -Xlen -s 0'
alias sshc='vim ~/.ssh/config'
alias xf='xmllint --format -'
alias hex='open -a "Hex Fiend"'

# I = case insensitive search
# R = process control characters (like terminal colours)
# X = disable termcap (usually disables clearing of screen)
# F = exit immediately if content doesn't fill the screen
export LESS=IR
export PAGER=less
export EDITOR=nvim

# For man pages, we need a maximum width, but it should
# be smaller if the terminal is smaller, so MANWIDTH needs
# to be calculated on the fly.  This still doesn't work
# well if the terminal is resized while man is open, but
# that doesn't seem solveable.
alias man='MANWIDTH=$((COLUMNS > 80 ? 80 : COLUMNS)) man'

if type jenv &>/dev/null; then
  eval "$(jenv init -)"
  export JAVA_HOME=$(jenv javahome)
fi

# export NVM_DIR="$HOME/.nvm"
# [ -s "/$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && . "/$HOMEBREW_PREFIX/opt/nvm/nvm.sh"  # This loads nvm
# [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export DOTNET_CLI_TELEMETRY_OPTOUT=true

export _ZO_ECHO=1 # print dir after changing
eval "$(zoxide init --cmd a zsh)"

# teach dive how to find non-standard docker socket locations (eg, for colima):
alias dive='DOCKER_HOST=$(docker context list --format json | jq -r "select(.Current == true) | .DockerEndpoint") dive'

alias k=kubectl
alias tf=terraform

eval "$(direnv hook zsh)"

# zprof
