# fzf - file generated by fzf install script, but tweaked.
# fzf installed by brew.

# Setup fzf
# ---------
# Brew already symlinks the binaries into an existing PATH location:
#if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
#  export PATH="$PATH:/usr/local/opt/fzf/bin"
#fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "/usr/local/opt/fzf/shell/key-bindings.bash"

